# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsuzuri" do
  version "0.1.1"

  on_macos do
    sha256 "cddfd71e87352e3372f1ccfcb2d669b9a5ffb8c61bdb309ff0ac3900e8ec5f3f"
    url "https://github.com/jaisuriya-11/tsuzuri/releases/download/v#{version}/tsuzuri-macos.tar.gz"
  end
  on_linux do
    on_intel do
      sha256 "40699c74ed1830c1fb7a5097928bf7a296b05cd65487d2463aeecfe147aeb0fa"
      url "https://github.com/jaisuriya-11/tsuzuri/releases/download/v#{version}/tsuzuri-linux.tar.gz"
    end
  end

  name "tsuzuri"
  desc "Terminal notes app that keeps your notes as plain Markdown files"
  homepage "https://github.com/jaisuriya-11/tsuzuri"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsuzuri"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsuzuri"]
    end
  end

  # No zap stanza required
end
